version: '3.4'

services:
  templatenext:
    container_name: templatenext-docker-container
    image: templatenext-docker:latest
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
